---
- name: Configure grafana on Ubuntu
  hosts: zeus
  become: yes

  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: sudo install adduser and libfontconfigl
      command: sudo apt install adduser libfontconfigl

    - name: wget grafana
      command: sudo wget https://dl.grafana.com/oss/release/grafana_7.2.0_amd64.deb

    - name: unpack grafana
      command: sudo dpkg -i grafana_7.2.0_amd64.deb

    - name: sudo install adduser and libfontconfigl
      command: sudo apt install adduser libfontconfigl

    - name: enable grafana
      command: sudo systemctl restart grafana-server

# sudo update -y
# sudo apt install adduser libfontconfigl
# wget https://dl.grafana.com/oss/release/grafana_7.2.0_amd64.deb
# sudo dpkg -i grafana_7.2.0_amd64.deb
  
