---
- hosts: zeus
  become: yes
  #become_user: root
  become_method: sudo

- name: Install Prometheus on Ubuntu
  tasks:
    - name: Add Prometheus APT Repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Add GPG Key for Prometheus APT Repository
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start Prometheus Service
      systemd:
        name: prometheus
        state: started
        enabled: yes
