---
- name: Create Custom Prometheus Exporter on Ubuntu
  hosts: exporter_server
  become: yes

  tasks:
    - name: Create a directory for the custom exporter
      file:
        path: /opt/custom_exporter
        state: directory
        mode: '0755'

    - name: Create the custom exporter script
      copy:
        content: |
          from http.server import HTTPServer, BaseHTTPRequestHandler
          import random
          import time

          class CustomExporter(BaseHTTPRequestHandler):
              def do_GET(self):
                  self.send_response(200)
                  self.send_header('Content-type', 'text/plain')
                  self.end_headers()
                  # Generate dummy metrics (replace with actual metrics logic)
                  metric = 'custom_metric_value ' + str(random.randint(1, 100))
                  self.wfile.write(metric.encode())

          if __name__ == '__main__':
              server = HTTPServer(('0.0.0.0', 8080), CustomExporter)
              server.serve_forever()
        dest: /opt/custom_exporter/custom_exporter.py
        mode: '0755'

    - name: Start the custom exporter
      command: python3 /opt/custom_exporter/custom_exporter.py
      async: 0
      poll: 0
      ignore_errors: yes
