---
- hosts: hrapp
  become: yes
  #become_user: root
  become_method: sudo
  
  vars:
    version: "2.46.0"

  tasks:
    - name: create a directory
      file:
        path: /home/ubuntu/workspace/hrapp/
        state: directory
 
        mode: 0755


    - name: Install GIT
      apt: 
        name: git  
      ignore_errors: yes 

    - name: installing docker-ce dependences 
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: adding GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Installing docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Making sure docker is up and running
      service:
        name: docker
        state: started
        enabled: yes
    #handlers:
  
    - name: Add docker user to a super user
      command: usermod -aG docker $USER
      
    - name: restart docker
      service: 
        name: docker 
        state: restarted



    - name: Remove directory
      file:
        state: absent
        path: /home/ubuntu/workspace
 
    - name: change directory
      shell:
        cmd: ls
        chdir: /home/ubuntu/workspace/hrapp
      

    - name: list content of pwd
      command: ls -ltr /home/ubuntu/workspace/hrapp


    - name: stop container if exist and running
      command: docker stop hrapp
      ignore_errors: yes

    - name: remove hrapp folder and its content if exists
      command: sudo rm -r hrapp
      ignore_errors: yes

    - name: Remove the container if exist and has been stopped by the previous module
      command: docker rm hrapp
      ignore_errors: yes 

    - name: Remove the image if exist , just to do a clean up before installation
      command: docker rmi hrapp
      ignore_errors: yes


    - name: Log into DockerHub using a custom config file
      docker_login:
        username: "{{username}}"
        password: "{{password}}" 

        
    - name: Pull an image
      community.docker.docker_image:
        name: japostina/hrapp
        source: pull
       # Select platform for pulling. If not specified, will pull whatever docker prefers.
        pull:
          platform: v1

   

    - name: Building Remove the image if exist , just to do a clean up before installation
      command: docker rmi hrapp:v1
      ignore_errors: yes

     
     
    - name: Log out of DockerHub
      docker_login:
        state: absent




    - name: building docker container image out of the docker image that has been built from the previous module
      ansible.builtin.command: docker run -p 80:5000 -e POSTGRES_HOST="{{POSTGRES_HOST }}" -e POSTGRES_USER="{{POSTGRES_USER }}" -e POSTGRES_DATABASE_NAME="{{ POSTGRES_DATABASE_NAME}}" -e POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD}}" -e TO_ADDRESS="{{TO_ADDRESS }}" -e SOURCE_ADDRESS="{{SOURCE_ADDRESS }}" -e AWS_REGION_NAME="{{AWS_REGION_NAME }}" -e AWS_ACCESS_NAME="{{ AWS_ACCESS_NAME}}" -e AWS_KEY_NAME="{{ AWS_KEY_NAME}}"
      






